
#include "grail/cli/CFG_TO_CNF.hpp"
#include "grail/cli/CFG_REMOVE_UNITS.hpp"
#include "grail/cli/CFG_REMOVE_EPSILON.hpp"

GRAIL_DECLARE_TOOL(CFG_TO_CNF)
GRAIL_DECLARE_TOOL(CFG_REMOVE_UNITS)
GRAIL_DECLARE_TOOL(CFG_REMOVE_EPSILON)
